### ISSUE TITLE
Pipelibe aborted! :(

### ISSUE THREAD

**Issue by jfbaquerocelis** [green-arrow/ember-cli-deploy-ssh-index#5]
Hi :+1: 

When I do the deployment with `ember-cli-deploy-ssh-index` following this guide https://emberigniter.com/deploy-ember-cli-app-amazon-s3-linux-ssh-rsync/

the console output is:

```
- 
|  |
|  +- ssh-index
- Attempting to connect to remote host: root@149.56.164.79:22
|
+- didFail
Error: All configured authentication methods failed
Error: All configured authentication methods failed
    at tryNextAuth (/home/nover/Documentos/Projects/tunana.co/nannysapp/node_modules/ember-cli-deploy-ssh-index/node_modules/ssh2/lib/client.js:294:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/home/nover/Documentos/Projects/tunana.co/nannysapp/node_modules/ember-cli-deploy-ssh-index/node_modules/ssh2/lib/client.js:473:5)
    at emitTwo (events.js:87:13)
    at SSH2Stream.emit (events.js:172:7)
    at parsePacket (/home/nover/Documentos/Projects/tunana.co/nannysapp/node_modules/ember-cli-deploy-ssh-index/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3647:10)
    at SSH2Stream._transform (/home/nover/Documentos/Projects/tunana.co/nannysapp/node_modules/ember-cli-deploy-ssh-index/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/home/nover/Documentos/Projects/tunana.co/nannysapp/node_modules/ember-cli-deploy-ssh-index/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
|
Pipeline aborted
```

My `deploy.js`:

``` javascript
if (deployTarget === 'production') {
    ENV.build.environment = 'production';
    // configure other plugins for production deploy target here
    ENV['build'] = {
      outputPath : 'tmp/tunana'
    };
    ENV['ssh-index'] = {
      username : 'root',
      host: '149.56.164.79',
      remoteDir : '/root/tunana',
      privateKeyFile : '~/.ssh/id_rsa',
      passphrase : '<my__passphrase>',
      allowOverwrite : true
    };
    ENV['rsync'] = {
      dest : '/root/tunana',
      host: 'root@149.56.164.79',
      delete : false
    }
  }
```

What is happen? Thanks for read <3

**Comment by green-arrow** [comment]
Are you able to manually SSH into the server with the SSH key and passphrase you have in the config? That error generally means whatever authentication you had provided was incorrect.

**Comment by jfbaquerocelis** [comment]
Hi @green-arrow! What is the passphrase that I must set? The remote passphrase or my private passphrase?

**Comment by green-arrow** [comment]
It should be the passphrase you used when generating your SSH key.

**Comment by jfbaquerocelis** [comment]
Yes, I do that. So, I created another ssh-key rigth now but it isn't run. This is very rare. I follow the guide step by step. also, I have changed the passphrase again and again.

My OS is  Linux Ubuntu 16.04
Node v4.5.0
NPM v.2.15.9

**Comment by michiel** [comment]
I have the exact same issue,

OS : Linux Ubuntu 16.04
Node  : 6.1.0
NPM : 3.6.8

I've also tested this on the command line,

```
sftp -v -i ~/.ssh/PRIVATE_KEY deploy@host
```

Which works and uses the specified private key,

```
debug1: identity file /home/USER/.ssh/PRIVATE_KEY-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
```

Server logs,

```
HOST sshd[25079]: Accepted publickey for deploy from X.X.X.X port 42136 ssh2: RSA SHA256
HOST sshd[25079]: pam_unix(sshd:session): session opened for user deploy by (uid=XX)
```

And enabling debug in node_modules/ssh2/lib/client.js,

```
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:12,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: publickey auth failed
```

For what it's worth, ember-cli-deploy-rsync (0.0.4) works with the same keyfile.

**Comment by michiel** [comment]
As a follow-up to this, I had the same issue with ember-cli-deploy-ssh2. After removing the deployment-user from the remote machine and re-creating it, adding the key and setting the permissions it now works fine.

So whatever the problem is - it's probably not related to this project.

**Comment by green-arrow** [comment]
Thanks for your follow-up @michiel, and my apologies for not responding.
